output:
  format: line-number

linters:
  enable:
    - goimports
    - revive
    - gofmt
    - misspell
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gochecknoinits
    - unconvert
    - unparam
    - exportloopref

run:
  timeout: 2m
